#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: zhenxi-v1-pv2
#  namespace: zhenxi-v1
#  finalizers:
#    - ubernetes.io/pv-protection
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 10Gi
#  hostPath:
#    path: /home/data/zhenxi-v1
#  persistentVolumeReclaimPolicy: Retain
#  volumeMode: Filesystem
#---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zhenxi-v1-redis2
  namespace: zhenxi-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#  volumeMode: Filesystem
#  volumeName: zhenxi-v1-pv2
---


#ZHENXI-V1-REDIS it works
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zhenxi-v1
  name: redis2
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-zhenxi-v1-redis2
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-zhenxi-v1-redis2
    spec:
      containers:
      - image: redis:6.2.6-alpine
        imagePullPolicy: Always
        name: redis2
        volumeMounts:
          - mountPath: /home/data/zhenxi-v1/redis/
            name: zhenxi-v1-redis2
      volumes:
        - name: zhenxi-v1-redis2
          persistentVolumeClaim:
            claimName: zhenxi-v1-redis2






